### ISSUE TITLE
Player Turn-Counter UI Element

### ISSUE THREAD

**Issue by CheapGSean** [HuskyGameDev/2020f-team3#13]
- Once https://github.com/HuskyGameDev/2020f-team3/issues/12 is implemented, add a temp UI element onto a Canvas to give a visual representation of the player's taken moves.
- Can be temp art or just text, just have it represented as a UI element.

**Comment by Wolfehh** [comment]
67f75fdcacab58cc727489f8c0d363bd9e4e2809
