### ISSUE TITLE
Add picker / new trash prefabs for individual trashes of different sprites

### ISSUE THREAD

**Issue by CheapGSean** [HuskyGameDev/2020f-team3#37]
To make full use of the several trash sprites that Keira has already made.

**Comment by Wolfehh** [comment]
Cant you just change the sprite image without editting the main prefab?

**Comment by CheapGSean** [comment]
I mentioned having separate prefabs in case each individual sprite needs to be slightly scaled per each one. The only difference between those trash prefabs and the original would just be the sprite and the scale.

**Comment by CheapGSean** [comment]
7819be08ee6ef9ba71ea14004aa7cec4ebf1c37b
